runtime: python37
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: webhook-v2.py

libraries:
- name: flask
  version: 1.0.3
  
env_variables:
  MYSQL_DNS:
  MYSQL_USER: root
  MYSQL_PASSWORD: Control2020++
